name: Github Actions

on: [pull_request]

jobs:
  rebase-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Rebase before merging?
        uses: cyberark/enforce-rebase@v2
        with:
          default-branch: ${{ github.base_ref }}
  lint-check:
    runs-on: ubuntu-latest
    container: predictivehireadmin/node-volta
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint Check
        run: pnpm lint
  unit-test:
    permissions: write-all
    runs-on: ubuntu-latest
    container: predictivehireadmin/node-volta
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Get changed files
        id: changed-files-as-space-delimited
        uses: jitterbit/get-changed-files@v1
      - name: Incremental Unit Test
        run: pnpm test:incremental --findRelatedTests ${{ steps.changed-files-as-space-delimited.outputs.all }}
      - uses: romeovs/lcov-reporter-action@v0.3.1
        # run even if last step fails
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./ci/coverage/lcov.info
          delete-old-comments: true
          title: Coverage Report for Modified Files Only of Current PR